builttoroam/device_calendar

- device_calendar.code-workspace
- device_calendar/example/lib/presentation/pages/calendar_events.dart
- device_calendar/ios/Classes/SwiftDeviceCalendarPlugin.swift
- device_calendar/lib/src/device_calendar.dart
- device_calendar/lib/src/models/event.dart
Note: Android code will need to change to account for filtering events by start and end date (no way to retrieve all events in iOS)
> Wire up ability to retrieve events using iOS

- device_calendar/example/lib/presentation/event_item.dart
- device_calendar/example/lib/presentation/pages/calendar_event.dart
- device_calendar/ios/Classes/SwiftDeviceCalendarPlugin.swift
- device_calendar/lib/src/common/constants.dart
- device_calendar/lib/src/device_calendar.dart
Also fixes example code to cater for scenarios where events might have missing info like null description etc
> Add ability to add or update an event in iOS

- device_calendar/ios/Classes/SwiftDeviceCalendarPlugin.swift
Also added placeholder error codes and messages
> Add ability to delete events and fixing bug when adding an event

- device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt
- device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/common/ErrorCodes.kt
- device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/common/ErrorMessages.kt
> Returning not authorized error when calendar permissions not granted

- device_calendar/CHANGELOG.md
- device_calendar/README.md
- device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt
- device_calendar/pubspec.yaml
Had some issues from rebasing etc in last release so recreated PR off a new branch
> 0.12+2 release

- device_calendar/example/ios/Runner.xcodeproj/project.pbxproj
- device_calendar/example/ios/Runner/Info.plist
- device_calendar/example_app/ios/Runner.xcodeproj/project.pbxproj
- device_calendar/example_app/ios/Runner/Info.plist
- device_calendar/ios/Classes/SwiftDeviceCalendarPlugin.swift
I suspected `calendar(withIdentifier:` to be the culprit but it turns out that the cast fix resolves the original problem
https://github.com/builttoroam/flutter_plugins/issues/94
> Compatibility fixes

- device_calendar/lib/src/models/recurrence_rule.dart
PR for https://github.com/builttoroam/flutter_plugins/issues/130
> [bugfix] Fix for setPositions null

- device_calendar/analysis_options.yaml
- device_calendar/example/analysis_options.yaml
- device_calendar/example/lib/presentation/event_item.dart
- device_calendar/example/lib/presentation/pages/calendar_event.dart
- device_calendar/example/lib/presentation/pages/calendar_events.dart
- device_calendar/example/test_driver/app_test.dart
- device_calendar/lib/src/common/error_messages.dart
- device_calendar/lib/src/device_calendar.dart
- device_calendar/lib/src/models/attendee.dart
- device_calendar/lib/src/models/calendar.dart
- device_calendar/lib/src/models/recurrence_rule.dart
- device_calendar/lib/src/models/result.dart
- device_calendar/pubspec.yaml
- device_calendar/test/device_calendar_test.dart
Added Pedantic package for code refactoring.
Issue: #143
> Code Refactoring

- device_calendar/CHANGELOG.md
- device_calendar/README.md
- device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt
- device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/DeviceCalendarPlugin.kt
- device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/models/Attendee.kt
- device_calendar/example/README.md
- device_calendar/example/android/build.gradle
- device_calendar/example/android/gradle/wrapper/gradle-wrapper.properties
- device_calendar/example/ios/Runner.xcodeproj/project.pbxproj
- device_calendar/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- device_calendar/example/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- device_calendar/example/ios/Runner/AppDelegate.swift
- device_calendar/example/lib/presentation/pages/calendar_event.dart
- device_calendar/example/lib/presentation/pages/event_attendee.dart
- device_calendar/example/lib/presentation/pages/event_attendees.dart
- device_calendar/ios/Classes/SwiftDeviceCalendarPlugin.swift
- device_calendar/lib/device_calendar.dart
- device_calendar/lib/src/common/calendar_enums.dart
- device_calendar/lib/src/models/attendee.dart
- device_calendar/lib/src/models/event.dart
- device_calendar/lib/src/models/platform_specifics/android/attendee_details.dart
- device_calendar/lib/src/models/platform_specifics/ios/attendee_details.dart
- device_calendar/lib/src/models/platform_specifics/ios/role.dart
- device_calendar/pubspec.yaml
**Issue:** #141
**Changes**
- Reads if an attendee is an organiser
- Attendee UI update
- Gradle/Swift update
**Possible Breaking Changes**
1. In `attendee.dart` file, `isRequired` boolean property has been replaced to `AttendeeRole` enum
2. New argument added for the `AttendeeRole` property
> Attendee ui

- device_calendar/CHANGELOG.md
- device_calendar/example/lib/presentation/event_item.dart
- device_calendar/example/lib/presentation/pages/calendar_event.dart
- device_calendar/example/lib/presentation/pages/calendar_events.dart
**Issue:** #149 
**Change:** Update on the example app to only view the events (ie. disabled widgets) for read-only calendars
**Note:** There might be a conflict with #148. If so, I'll rebase and resolve conflicts when either one gets merged.
> Readonly noedit

- device_calendar/CHANGELOG.md
- device_calendar/lib/src/device_calendar.dart
- device_calendar/pubspec.yaml
> url property is now null-aware

- device_calendar/CHANGELOG.md
- device_calendar/lib/src/device_calendar.dart
- device_calendar/pubspec.yaml
Fix from #158 with updated version/changelog
> Allday hotfix

- device_calendar/example/lib/presentation/pages/calendar_events.dart
Quick UI fix to hide an add event button for read-only calendars
> Readonly_noadd

- azure-pipelines.yml
Procedures are:
1. Change directory to `[Flutter_Install_Path]/flutter/.pub-cache/`
2. Create `credentials.json` file with required tokens as a JSON string
Applied for both pre-release and stable release
> Pipeline credentials

- device_calendar/CHANGELOG.md
- device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt
- device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/DeviceCalendarPlugin.kt
- device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/common/Constants.kt
- device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/common/ErrorMessages.kt
- device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/models/Account.kt
- device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/models/Attendee.kt
- device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/models/Calendar.kt
- device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/models/Reminder.kt
- device_calendar/example/android/app/src/main/kotlin/com/builttoroam/devicecalendarexample/MainActivity.kt
- device_calendar/example/lib/presentation/date_time_picker.dart
- device_calendar/example/lib/presentation/event_item.dart
- device_calendar/example/lib/presentation/pages/calendar_add.dart
- device_calendar/example/lib/presentation/pages/calendar_event.dart
- device_calendar/example/lib/presentation/pages/calendar_events.dart
- device_calendar/example/lib/presentation/pages/calendars.dart
- device_calendar/example/lib/presentation/pages/event_attendee.dart
- device_calendar/example/lib/presentation/recurring_event_dialog.dart
- device_calendar/lib/src/common/calendar_enums.dart
- device_calendar/lib/src/device_calendar.dart
- device_calendar/lib/src/models/attendee.dart
- device_calendar/lib/src/models/calendar.dart
- device_calendar/lib/src/models/event.dart
- device_calendar/lib/src/models/platform_specifics/android/attendee_details.dart
- device_calendar/lib/src/models/platform_specifics/ios/attendee_details.dart
- device_calendar/lib/src/models/recurrence_rule.dart
- device_calendar/pubspec.yaml
> Flutter format & Android code clean up

- android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt
Fixed bug giving error when user tried to add a calendar while gmail is open.
> Bug fix when adding new calendar.

- lib/src/models/event.dart
Hi again @nickrandolph, here's the new PR to remove duplicate code.
Thanks
> Removing duplicate code in event.dart

- README.md
> added enable proguard when building release version to README

- lib/src/models/platform_specifics/android/attendee_details.dart
- lib/src/models/platform_specifics/ios/attendee_details.dart
Hello,
This is fix for the issue https://github.com/builttoroam/device_calendar/issues/312
> Correct attendance status json key

- lib/src/models/event.dart
Fixes #266 and also adds `url` parameter.
> Add location and url to constructor

- .github/workflows/dart.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- CHANGELOG.md
I'm trying to rewrite the current CI/CD using Github Actions
So far CI is simple enough
Things to work on:
> Using Github Actions

- .github/workflows/prerelease.yml
- .github/workflows/release.yml
> Redo Publish part 2

- azure-pipelines.yml
- lib/src/models/event.dart
- test/device_calendar_test.dart
Fixes #320 
- Fixes attribute inconsistencies between `event.toJson` and `event.fromJson`.
- Adds checks in event serialization test for remaining attributes
- Adds new task to run test CI pipeline
> Fix event serialization and run tests in CI pipeline

- android/build.gradle
- android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt
- example/android/app/build.gradle
- example/android/app/src/main/AndroidManifest.xml
- example/android/build.gradle
- example/android/gradle.properties
- example/android/gradle/wrapper/gradle-wrapper.properties
Gradle, kotlin and other packages upgraded to the latest versions
Targeting android 31
> Upgrade for gradle

- example/integration_test/integration_test.dart
- example/integration_test/integration_test_android.dart
- example/integration_test/ios.sh
- example/ios/Flutter/AppFrameworkInfo.plist
- example/ios/Podfile.lock
- example/ios/Runner.xcodeproj/project.pbxproj
The project has an Android integration test that does not yet run on iOS. This PR adds the ability to easily execute the test against an iOS device, currently a simulator.
> iOS integration test execution framework

- README.md
- android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt
- android/src/main/kotlin/com/builttoroam/devicecalendar/DeviceCalendarPlugin.kt
- android/src/main/kotlin/com/builttoroam/devicecalendar/models/Attendee.kt
- android/src/main/kotlin/com/builttoroam/devicecalendar/models/Calendar.kt
- example/ios/Runner/Info.plist
- example/lib/presentation/pages/calendar_event.dart
- example/lib/presentation/pages/event_attendee.dart
- ios/Classes/SwiftDeviceCalendarPlugin.swift
- lib/src/common/channel_constants.dart
- lib/src/device_calendar.dart
- lib/src/models/attendee.dart
- lib/src/models/platform_specifics/android/attendee_details.dart
- lib/src/models/platform_specifics/ios/attendee_details.dart
Replaces #335. 
cherry picked commit 87710e0f0e084624aac8b477b40d9f1bd42790a1 into the latest branch for convenience.
> Change attendance status

- CHANGELOG.md
- pubspec.yaml
> 4.2 final prep

- CHANGELOG.md
- example/lib/presentation/event_item.dart
- example/lib/presentation/pages/calendar_event.dart
- example/pubspec.yaml
- pubspec.yaml
> Release 4.3.2: packages cleanup

- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- android/build.gradle
- example/android/app/build.gradle
- example/android/build.gradle
- example/lib/presentation/date_time_picker.dart
- example/lib/presentation/pages/calendar_event.dart
- example/lib/presentation/pages/calendar_events.dart
- example/lib/presentation/pages/calendars.dart
- example/pubspec.yaml
- pubspec.yaml
Note: this branch is being used to "kickstart" prereleases & releases. Will merge to `develop` once a stable build is released.
> fix github actions
