device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt, device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/DeviceCalendarPlugin.kt, device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/common/ErrorCodes.kt, device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/common/ErrorMessages.kt, device_calendar/example/lib/presentation/event_item.dart, device_calendar/example/lib/presentation/pages/calendar_events.dart, device_calendar/example/lib/presentation/pages/calendars.dart, device_calendar/lib/device_calendar.dart, device_calendar/lib/src/common/constants.dart, device_calendar/lib/src/common/error_codes.dart, device_calendar/lib/src/common/error_messages.dart, device_calendar/lib/src/device_calendar.dart, device_calendar/lib/src/models/attendee.dart, device_calendar/lib/src/models/event.dart, device_calendar/lib/src/models/results/base_result.dart
You might want to add NOT_ALLOWED error code to iOS and handle the isReadOnly flag for the calendar, when user tries to do a CRUD operation on the calendar
=> Handling platform errors. Unifying droid and iOS error codes

device_calendar/lib/src/device_calendar.dart, device_calendar/lib/src/models/event.dart
This should go in, before we release the plugin, as it' has a critical fix for retrieving calendar events
=> Fixing an issue with retrieving calendar events logic. Adding eventId as an optional parameter in the Event object constructor.

device_calendar/android/build.gradle, device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/DeviceCalendarPlugin.kt
This PR will fix issue https://github.com/builttoroam/flutter_plugins/issues/68
and issue https://github.com/builttoroam/flutter_plugins/issues/67
=> Fixed Kotlin Gradle plugin version and Type mismatch error

device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt
This is the fix I made to address the issue with the plugin "stealing" the permission from other plugins. Note that I didn't spend a lot of time looking at the code--I just know that it should be returning false when it isn't handling the permission.
=> Fix issue with calendar stealing permission notifications

device_calendar/CHANGELOG.md, device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt, device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/DeviceCalendarPlugin.kt, device_calendar/pubspec.yaml
@MaikuB fixed an issue where the plugin causes the app to crash when trying to execute background updates using the background fetch plugin. Issue: #101
=> accept nullable activity that can happen during headless execution @MaikuB 

device_calendar/CHANGELOG.md, device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt, device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/common/Constants.kt, device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/models/Calendar.kt, device_calendar/example/README.md, device_calendar/example/lib/presentation/pages/calendars.dart, device_calendar/ios/Classes/SwiftDeviceCalendarPlugin.swift, device_calendar/lib/src/models/attendee.dart, device_calendar/lib/src/models/calendar.dart, device_calendar/lib/src/models/event.dart, device_calendar/pubspec.yaml
**Improvements**
* Added some information and examples (issue #119)
* Added "Read-only" text to read-only property summaries (issues #121, #122)
* Both platforms will default the event title to "New Event" if it is null (issue #126)
* Applied Android support for isDefault calendar (#145)
**Notes**
I've updated the changelog without a date, I'll make sure to update it before we release this.
=> Minor enhancements

device_calendar/CHANGELOG.md, device_calendar/README.md, device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt, device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/DeviceCalendarPlugin.kt, device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/common/Constants.kt, device_calendar/example/lib/presentation/event_item.dart, device_calendar/example/lib/presentation/pages/calendar_event.dart, device_calendar/example/lib/presentation/pages/calendar_events.dart, device_calendar/example/lib/presentation/recurring_event_dialog.dart, device_calendar/ios/Classes/SwiftDeviceCalendarPlugin.swift, device_calendar/lib/src/common/calendar_enums.dart, device_calendar/lib/src/device_calendar.dart
Issue No: #108 
- Event delete instance (and following instances if wanted)
- Added note that deleting instance and the following of an event will take time to be synced
- Properly retrieves the correct calendar
- Removed `Custom` item from `DayOfWeekGroup` enum
=> Delete instance + DayOfWeekGroup enum update

device_calendar/CHANGELOG.md, device_calendar/README.md, device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt, device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/DeviceCalendarPlugin.kt, device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/common/Constants.kt, device_calendar/android/src/main/kotlin/com/builttoroam/devicecalendar/models/Event.kt, device_calendar/example/lib/presentation/pages/calendar_event.dart, device_calendar/ios/Classes/SwiftDeviceCalendarPlugin.swift, device_calendar/lib/src/device_calendar.dart, device_calendar/lib/src/models/event.dart
- The time and time zone will be set to whatever the input was
- Updated to use `event.toJson()` to parse event object into JSON string instead of manually parsing it in the `createOrUpdateEvent()` method
- Added `reminders` property in `Event` model constructor
=> Timezone support

ios/Classes/SwiftDeviceCalendarPlugin.swift
=> iOS daysOfWeek

android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt, android/src/main/kotlin/com/builttoroam/devicecalendar/DeviceCalendarPlugin.kt, azure-pipelines.yml, example/android/app/build.gradle, example/lib/presentation/pages/calendar_events.dart, example/lib/presentation/pages/calendars.dart, ios/Classes/SwiftDeviceCalendarPlugin.swift, lib/src/common/channel_constants.dart, lib/src/device_calendar.dart
Fix for https://github.com/builttoroam/device_calendar/issues/225 issue
=> add deleteCalendar() function

android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt
Currently this plugin requires Android activity in a lot of places. This prevents plugin from being used in the background when there is no activity present.
This PR removes all references to the activity where one is not needed. Only permission request is left, which does require activity.
=> only use Android activity for permissions request

android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt, example/android/app/build.gradle, example/ios/.gitignore, example/ios/.symlinks/plugins/device_calendar, example/ios/.symlinks/plugins/flutter_native_timezone, example/ios/Podfile.lock, example/ios/Runner.xcodeproj/project.pbxproj, example/lib/presentation/date_time_picker.dart, example/lib/presentation/event_item.dart, example/lib/presentation/input_dropdown.dart, example/lib/presentation/pages/calendar_add.dart, example/lib/presentation/pages/calendar_event.dart, example/lib/presentation/pages/calendar_events.dart, example/lib/presentation/pages/calendars.dart, example/lib/presentation/recurring_event_dialog.dart, example/test_driver/app_test.dart, lib/device_calendar.dart, lib/src/device_calendar.dart, lib/src/models/attendee.dart, lib/src/models/event.dart, lib/src/models/platform_specifics/android/attendance_status.dart, lib/src/models/platform_specifics/android/attendee_details.dart, lib/src/models/platform_specifics/ios/attendance_status.dart, lib/src/models/platform_specifics/ios/attendee_details.dart, lib/src/models/recurrence_rule.dart, lib/src/models/reminder.dart, pubspec.yaml, test/device_calendar_test.dart
Android implementation should now work with Timezone logic. So should example build. 
Currently haven't looked on iOS.
=> Timezone implementation

lib/src/device_calendar.dart, pubspec.yaml
1. In case the application initializes its own timezone by setting the local timezone as the current device timezone, it should be possible to omit the initialization of the timezone database so that it doesn't default to UTC.
2. Update `flutter_native_timezone` library to the latest 2.0.0 version.
=> Make timezone database initialization optional

lib/src/models/event.dart
Changed key names to 'eventStartDate' and 'eventEndDate'.
Fix for #315
=> Event.fromJson 'start'-key assignment fixed

ios/Classes/SwiftDeviceCalendarPlugin.swift, lib/src/models/event.dart
I should have separated these into two pull requests but I believe they are both worthwhile fixes; if you disagree about the source fallbacks then it would be great if you could at least re-add the url parameter.
In production I'm seeing errors and a failure to create scheduled notifications on many devices, as it seems in more recent iOS versions there is often no local calendar. It would be even better if there were a way to query sources directly from flutter, but that would complicate things and is probably overkill in most cases - I'm going to guess that 99% of users just use the default iCloud calendar.
=> iOS Source fallbacks and re-add url parameter

android/build.gradle, android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt, android/src/main/kotlin/com/builttoroam/devicecalendar/DeviceCalendarPlugin.kt
Why: It seems that the V2 embedding was not applied to the plugin file, Just to the manifest. 
What: This PR adds support for v2 embedding.
Documentation:
https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration
https://csdcorp.com/blog/coding/handling-permission-requests-in-android-for-flutter-plugins/
Related issues:
#326
=> Feat: v2 embedding

.github/workflows/prerelease.yml, .github/workflows/release.yml
Continuing #346
- Don't create github releases if it failed to publish
- publication test: Added the flutter environment so credentials are reachable
=> Updating CI/CD

.github/workflows/prerelease.yml, .github/workflows/release.yml
Continuing #346 
With this fix we should be able to locate the credentials.
Unless it isn't there, which maybe we should need to set the credentials into Github's env secrets.
=> pub cache location fix

example/lib/presentation/date_time_picker.dart, example/lib/presentation/event_item.dart, example/lib/presentation/pages/calendar_event.dart, example/lib/presentation/recurring_event_dialog.dart, lib/src/models/event.dart, lib/src/models/platform_specifics/android/attendee_details.dart, lib/src/models/platform_specifics/ios/attendee_details.dart, test/device_calendar_test.dart
- `Availability` now default to busy if you don't have one, also makes it not `required`. 
ie. Less code need to be edited when upgrading to v4.
- Other formatting and warning fixes as prompted by flutter's checks
Since this benefits migration from previous versions I hope to merge this before v4 main release.
=> Set default Availability to Busy, and minor fixes

.github/workflows/prerelease.yml, .github/workflows/release.yml
Part of #346 
@nickrandolph added the credentials to Github's secrets. (Thanks!)
If this runs we will disable `dry_run` next time.
=> using secrets

.github/workflows/dart.yml, lib/src/models/event.dart, test/device_calendar_test.dart
Part of #346 
Fixing https://github.com/builttoroam/device_calendar/actions/runs/1490200641
- Matching `fromJson` and `toJson` behaviors for Events
- Somehow `TZDateTime` doesn't store its time consistently. Changed the test to check the actual time instead of the values stored.
- Added `flutter test` to CI (build)
=> Fix for flutter test

.github/workflows/prerelease.yml, .github/workflows/release.yml
Part of #362 
Referencing [xvrh's work](https://github.com/xvrh/lottie-flutter).
@nickrandolph also pointed out our json's formatting might have caused problems. Now we wrap it in a file properly so hopefully it works better now.
Also, their pipeline [worked](https://github.com/xvrh/lottie-flutter/runs/3704939536?check_suite_focus=true) so I'm a bit more confident this time around 🤞
=> Redo flutter publish

.github/workflows/dart.yml
iOS builds are usually longer.
This should make them go parallel, saving time.
=> parallel testing

CHANGELOG.md, pubspec.yaml
Trying to make #368 able to merge.
And other wordy fixes.
=> V4.0.0 final prep

CHANGELOG.md, android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt, android/src/main/kotlin/com/builttoroam/devicecalendar/DeviceCalendarPlugin.kt, android/src/main/kotlin/com/builttoroam/devicecalendar/models/Event.kt, ios/Classes/SwiftDeviceCalendarPlugin.swift, pubspec.yaml
Discovered in #374 by @nitinjavakid
Continuing #316 and originated from #297, we haven’t renamed all labels when migrating all the variables.
I’ve tested on Android but cannot get an iOS device to test yet. Can someone help test it?
=> Emergency fix: not getting times from events

CHANGELOG.md, example/README.md, lib/src/models/event.dart
Part of #387 
Catching old `event` args and send them through as normal.
Will send an `Excemption` if activated, so people can catch and fix things.
Also added example JSON and (probable) files list related to `Event` JSON
=> old args convertor

android/build.gradle
[Fix][Android] Fix the andoidx.appcompat that is incompatibility caused compile error when building apk in release mode
1.error: 'AAPT: error: resource android:attr/lStar' not found when building apk in release mode
2.causes: androidx.appcompat incompatibility
Signed-off-by: zhuyangyang <yangyang.zhu@pplingo.com>
=>  [Fix][Android] Fix the compile error caused by andoidx.appcompat when building apk in release mode

.github/workflows/dart.yml, example/android/app/build.gradle, example/android/app/proguard-rules.pro
Fixes problem found when solving #401  and #399 
1. Proguard for `example` app
2. Tests `flutter build apk` as well, because somehow it behaves quite differently to  `flutter build appbundle`. That's why we did not notice the problems.
=> Fixes for better testing

android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt, android/src/main/kotlin/com/builttoroam/devicecalendar/DeviceCalendarPlugin.kt, android/src/main/kotlin/com/builttoroam/devicecalendar/EventStatusSerializer.kt, android/src/main/kotlin/com/builttoroam/devicecalendar/common/Constants.kt, android/src/main/kotlin/com/builttoroam/devicecalendar/models/Event.kt, android/src/main/kotlin/com/builttoroam/devicecalendar/models/EventStatus.kt, example/lib/presentation/event_item.dart, example/lib/presentation/pages/calendar_event.dart, ios/Classes/SwiftDeviceCalendarPlugin.swift, lib/src/common/calendar_enums.dart, lib/src/models/event.dart, test/device_calendar_test.dart
Android: https://developer.android.com/reference/android/provider/CalendarContract.EventsColumns#STATUS
iOS: https://developer.apple.com/documentation/eventkit/ekevent/1507158-status
This property is useful when the organizer provides a confirmation of the meeting to the attendees. There is more information about it in this [link](https://www.rfc-editor.org/rfc/rfc5545#section-3.8.1.11)
In iOS it seems to be read only. That's the reason I add a platform verification in example, allowing EventStatus edition only in Android. But I am not sure if there is a way to edit the status property in iOS side.
I tested it in both platforms
=> Add EventStatus property to Event

CHANGELOG.md, pubspec.yaml
- bumped version to `4.2.1` and populated changelog
- updated `timezone` to [`0.9.0`](https://pub.dev/packages/timezone/changelog#090) (for details see #437)
- updated `collection` to [`1.16.0`](https://pub.dev/packages/collection/changelog#1160) (no breaking changes)
- updated `sprintf` to [`6.0.2`](https://pub.dev/packages/sprintf/changelog) (no breaking changes)
- updated `flutter_lints` to [`2.0.1`](https://pub.dev/packages/flutter_lints/changelog#201) (no breaking changes)
=> Updated multiple underlying dependencies (closes #437).

android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt, android/src/main/kotlin/com/builttoroam/devicecalendar/DeviceCalendarPlugin.kt
CalendarDelegate is always created. In the background without binding. Since the permissions cannot then be queried in the isolate, the check is suspended in this case.
=> Allows the plugin to be used in the background / an isolate

example/lib/presentation/event_item.dart, example/lib/presentation/pages/calendar_event.dart, example/pubspec.yaml, lib/device_calendar.dart, lib/src/models/event.dart, pubspec.yaml
No more hacky `timezone` imports needed, now that the files are (correctly) exported.
Also removed packages that ain't essential, slimming it down
=> packages cleanup

ios/Classes/SwiftDeviceCalendarPlugin.swift
Fixed fullDay with DateRange events creation (not only one fullday events possible to create) Timezone should be set only if event is not full day
=> Fixed All day events start time may be incorrect (iOS only) #337

ios/Classes/SwiftDeviceCalendarPlugin.swift
Tthe current Swift-implentation of `requestPermissions` does not return if permissions have already been granted. Thus, if it is called more than once, subsequent attempts try to request permissions again, causing the call to fail with a 400-error (`To create or update an all day event you must provide calendar ID, event with a title and event's start date`).
There was already a second implementation of `requestPermissions` which wasn't used anywhere but correctly short-circuits if permissions have already been granted so I thought it would be better to use that.
EDIT: Actually, the errors seem to be caused by an error on my end. Regardless, this change seems reasonable to me, if less urgent :)
=> Remove faulty requestPermissions implementation in favor of working one

CHANGELOG.md, android/src/main/kotlin/com/builttoroam/devicecalendar/CalendarDelegate.kt, example/lib/presentation/pages/calendar_event.dart, lib/src/models/event.dart, pubspec.yaml
Issue #470 
Error
`CalendarDelegate.kt:784:9 'when' expression must be exhaustive, add necessary 'DAILY', 'HOURLY', 'MINUTELY', 'SECONDLY' branches or 'else' branch instead`
Fix
`when (rfcRecurrenceRule.freq) {
Freq.WEEKLY, Freq.MONTHLY, Freq.YEARLY -> {
recurrenceRule.daysOfWeek = rfcRecurrenceRule.byDayPart?.mapNotNull {
DayOfWeek.values().find { dayOfWeek -> dayOfWeek.ordinal == it.weekday.ordinal }
}?.toMutableList()
}
else -> recurrenceRule.daysOfWeek = null
}`
Added 'else' so that it is compliant with Kotlin 1.7.21.
=> Added 'else' in compliance with Kotlin 1.7.21.

ios/Classes/SwiftDeviceCalendarPlugin.swift
Fix for https://github.com/builttoroam/device_calendar/issues/452
The current implementation of receiving events on iOS does not take into account that `EKEventStore` returns events for a maximum of 4 years ([doc](https://developer.apple.com/documentation/eventkit/ekeventstore/1507479-predicateforevents#discussion)). Accordingly, when specifying a range of more than 4 years, not all events are received.
=> Fix retrieving events for more than 4 years range

README.md, android/build.gradle, android/proguard-rules.pro, example/android/build.gradle
Solves issue on Android where user needs to add proguard rules. This PR will add proguard rules to the plugin.
=> add proguard rules

example/android/app/build.gradle, example/android/build.gradle
Trying to fix #496 #483 and others
=> gradle fix

.github/workflows/dart.yml, README.md, android/build.gradle, example/android/app/build.gradle, ios/Classes/SwiftDeviceCalendarPlugin.swift
Issue #490 
A distinction between write-only access and full access has been made since iOS17.
https://developer.apple.com/documentation/technotes/tn3152-migrating-to-the-latest-calendar-access-levels
This PR obtains full access, but it may be inappropriate if you intend to be able to handle write-only access separately.
=> Request FullAccess on iOS17+

.github/workflows/dart.yml, CHANGELOG.md, README.md, android/build.gradle, example/lib/presentation/pages/calendar_event.dart, ios/Classes/SwiftDeviceCalendarPlugin.swift, pubspec.yaml
Cherry-pick referencing this [issue](https://github.com/builttoroam/device_calendar/pull/497).
=> Cherry pick request FullAccess on iOS17+ (#497)

android/build.gradle
* Fix: Add namespace to the release version for compatibility whit AGP 8.0+ (Fixes #523 #527)
Co-authored-by: ashwani <ashwani@users.noreply.github.com>
=> Add support for AGP 8.0 on the release branch Peng1104/device_calendar#1

.github/workflows/dart.yml, .github/workflows/prerelease.yml, .github/workflows/release.yml
Uses the official pipeline instead of manual tokens
ie. no more expired token roadblocks
https://dart.dev/tools/pub/automated-publishing
=> WIP: Pipeline update
